name: build

on: push

jobs:
  build:
    name: build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.17'
          channel: 'stable'
      - run: flutter pub get
      - name: android build
        if: ${{ matrix.os == 'ubuntu-latest' }}

        # sdkmanager not present in github actions, results in following error:
        # "No version of NDK matched the requested version 21.0.6113669. Versions available locally: 21.3.6528147"
        # TODO remove workaround when https://github.com/flutter/flutter/issues/53657 resolved
        run: |
          sed -i '30i\ \ \ \ ndkVersion "21.3.6528147"' android/app/build.gradle
          flutter build apk --debug
      - name: ios build
        if: ${{ matrix.os == 'macos-latest' }}
        run: flutter build ios --debug --no-codesign
